/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.registration;

/**
 *
 * @author TeamNextOra
 */
public class ModificationPane extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationPane
     */
    public ModificationPane() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        updateOfficers1 = new gui.registration.UpdateOfficers();
        updateStudent1 = new gui.registration.UpdateStudent();

        setPreferredSize(new java.awt.Dimension(1180, 625));

        jTabbedPane1.addTab("Officer Modifcation", updateOfficers1);
        jTabbedPane1.addTab("Student Modifcation", updateStudent1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1173, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private gui.registration.UpdateOfficers updateOfficers1;
    private gui.registration.UpdateStudent updateStudent1;
    // End of variables declaration//GEN-END:variables
}
