/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.registration;

/**
 *
 * @author savaa
 */
public class RegistrationPane extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationPane
     */
    public RegistrationPane() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        gurdientRegistration1 = new gui.registration.GurdientRegistration();
        principleRegistration1 = new gui.registration.PrincipleRegistration();
        teacherRegistration1 = new gui.registration.TeacherRegistration();
        gurdientRegistration2 = new gui.registration.GurdientRegistration();
        studentRegistration1 = new gui.registration.StudentRegistration();

        jTabbedPane1.addTab("Admin Registration", gurdientRegistration1);
        jTabbedPane1.addTab("Principle Registration", principleRegistration1);
        jTabbedPane1.addTab("Teacher Registration", teacherRegistration1);
        jTabbedPane1.addTab("Gurdient Registration", gurdientRegistration2);
        jTabbedPane1.addTab("Student Registration", studentRegistration1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.registration.GurdientRegistration gurdientRegistration1;
    private gui.registration.GurdientRegistration gurdientRegistration2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private gui.registration.PrincipleRegistration principleRegistration1;
    private gui.registration.StudentRegistration studentRegistration1;
    private gui.registration.TeacherRegistration teacherRegistration1;
    // End of variables declaration//GEN-END:variables
}
